### ISSUE TITLE
deploy.ts

### ISSUE THREAD

**Issue by salvaDalle** [DeDogmaDao/dt-contracts#23]
https://github.com/DeDogmaDao/dt-contracts/blob/05a2c0cf491f8a1a5e7ec0ea9e10de06be8cd2e0/src/contracts/readme.md?plain=1#L24

hi , I think I found a very small problem. There should be setup.ts instead of deploy.ts . Thank you for your attention

**Comment by FlokiBB** [comment]
@salvaDalle, thanks for your attention. We should update our readme files because we have a lot of changes.
