### ISSUE TITLE
transfer it to near of uint8

### ISSUE THREAD

**Issue by FlokiBB** [DeDogmaDao/dt-contracts#25]
https://github.com/DeDogmaDao/dt-contracts/blob/06e9af1ab56ac77f746c9f59ccdd14c5492d3e6c/src/contracts/DAOTreasury.sol#L24

**Comment by dante6363** [comment]
can u explain about this issue? i think it isnt an issue

**Comment by FlokiBB** [comment]
in the EVM world, there is a lot of trick for gas optimization and variable packing is one of them this issue trying to make variable packing 

https://medium.com/coinmonks/gas-optimization-in-solidity-part-i-variables-9d5775e43dde
